name: Docker Image CI
run-name: ${{ github.actor }} execute after pushes 🚀
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Login Docker
      run: docker login -u ahlirobot -p Guruahli2021@
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ahlirobot/yolov9website:latest
    - name: Push the Docker image
      run: docker push ahlirobot/yolov9website:latest
    - name: run the docker
      run: docker run -d --name yolov9website -p80:80 ahlirobot/yolov9website:latest
